### ISSUE TITLE
Proposal: ORM to test

### ISSUE THREAD

**Issue by francescobianco** [emilianozublena/mikro-php#1]
I'm so sorry to disturb you, I would kindly ask you if you could test this library in your project! 
https://github.com/javanile/moldable
With the purpose of knowing my project and understanding if it can be integrated into yours!
To thank you for your availability I am observing your project and giving a star

Install via composer
```
composer require javanile/moldable
```

I ask you if we can help each other

**Comment by emilianozublena** [comment]
It should be easy to implement this, since every dependency that this framework has are loaded through the Service Manager (IoC container)... i dont really see the point of integrating it if i dont have any use case...

Or maybe you are asking me to integrate it and deliver this framework with that ORM?

**Comment by emilianozublena** [comment]
@francescobianco did you have any chance to look at my last message? if there's nothing else to say, ill close this PR.

cheers!
